version: "3"

services:
#   TODO: fix hot reload and some other problems
#  frontend:
#    build:
#      dockerfile: Dockerfile
#      context: ./frontend
#    environment:
#      CHOKIDAR_USEPOLLING: "true"
#    ports:
#      - 8080:8080
#    #    volumes:
#    #      - /app/node_modules
#    #      - ./frontend/web:/app
#    volumes:
#      - /app/node_modules
#      - ./frontend:/app
#    env_file:
#      - ./frontend/.env
#    depends_on:
#      - backend
#    networks:
#      - web

# TODO: fix hot reload and some other problems
#  backend:
#    build:
#      dockerfile: Dockerfile
#      context: ./backend
#    ports:
#      - 8081:8081
#    volumes:
#      - ./backend:/app # named volume
#      - /app/node_modules # anonymous volume for node_modules only
#    #    volumes:
#    #      - /app/node_modules # anonymous volume for node_modules only
#    #      - ./backend:/app # named volume
#    #    volumes:
#    #      - .:/usr/app # named volume
#    #      - /usr/app/node_modules # anonymous volume for node_modules only
#    env_file:
#      - ./backend/.env
#    depends_on:
#      - postgres
#    networks:
#      - web

  postgres:
    image: postgres:13.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - ./backend/.env
    networks:
      - postgres

  # pgadmin url - localhost:8082
  pgadmin:
    links:
      - postgres:postgres
    image: dpage/pgadmin4
    ports:
      - "8082:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - ./backend/.env
    networks:
      - postgres

volumes:
  node_modules:

networks:
  web:
    driver: bridge
  postgres:
    driver: bridge
